kind: pipeline
name: default

steps:
  - name: build
    image: plugins/gcr
    settings:
      repo: gcr.io/harambe-6/harambe-6
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      json_key:
        from_secret: GCLOUD_CREDENTIALS
  - name: replace-deployment-text
    image: jeremyaherzog/drone-text-replacement
    settings:
      filename: deployment.yml
      version: ${DRONE_COMMIT_SHA}
  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_token:
        from_secret: KUBE_TOKEN
      kubernetes_cert:
        from_secret: KUBE_CA
      kubernetes_server:
        from_secret: KUBE_SERVER
    command:
      - apply -f deployment.yml
