kind: pipeline
name: default

steps:
  # - name: build
  #   image: plugins/docker
  #   settings:
  #     username:
  #       from_secret: DOCKER_USERNAME
  #     password:
  #       from_secret: DOCKER_PASSWORD
  #     repo: jeremyaherzog/harambe-6
  #     tags:
  #       - latest
  #       - ${DRONE_COMMIT_SHA}
  #   when:
  #     branch:
  #     - master
  #     event:
  #     - push
  - name: deploy
    image: hashicorp/terraform
    environment:
      DO_TOKEN:  
        from_secret: DO_TOKEN
      IEX_KEY:  
        from_secret: IEX_KEY
      TF_STATE_ACCESS_KEY:
        from_secret: TF_STATE_ACCESS_KEY
      TF_STATE_SECRET_KEY:
        from_secret: TF_STATE_SECRET_KEY
    commands:
      - apk add --update make
      - printenv > .env
      - make tf-init
      - mkdir -p ~/.kube
      - touch ~/.kube/config
      - printf 'yes' | make tf-deploy GIT_TAG=$DRONE_COMMIT_SHA
    when:
      branch:
      - master
      event:
      - push
